### ISSUE TITLE
🔗[BROKEN LINK] In docs/participate/iron-age-testnet.md Page

### ISSUE THREAD

**Issue by NoName4Me** [dominant-strategies/quai-docs#103]
**Where is the broken link?**
Page: docs/participate/iron-age-testnet.md
Lines: 25

**What word(s) is/are incorrectly linked?**
Contract Deployment Tutorial(s)

**What is the CURRENT, broken link address you are directed to?**
/develop/tutorials/solidity.md

**What is the CORRECT, updated link address you should have been directed to (If you don't know, put IDK)?**
IDK

**Comment by Juuddi** [comment]
Fixed by #101
