### ISSUE TITLE
[TOPIC]: data-dir and docroot info added to docs

### ISSUE THREAD

**Issue by dubrado** [dominant-strategies/quai-docs#47]
### Bug Description

From Discord:

_`Question: the hardware specs mentioned having a 3TB hard drive. If I change the data-dir and docroot paths in the config.toml file........ actually let me re-phrase that. Are those two paths where it needs 3TB of drive space?`_

We answered this already in Discord but wondering if we can get more clarification added to the docs about this as others may want to pick a non-default location and they should know what else they need to change and reminder about that location needing the storage for the DB

### Version

n/a

### Environment

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

### Relevant Code or Logs

n/a

**Comment by dubrado** [comment]
not a bug, sorry missed that label.

**Comment by Juuddi** [comment]
Closing as the `config.toml` file is no longer relevant. This will be specified in the additional flags section coming in a future PR.
