### ISSUE TITLE
🗒️[UPDATE CONTENT] Update FAQ Page

### ISSUE THREAD

**Issue by Djadih** [dominant-strategies/quai-docs#74]
**What page needs its content updated?**
GPU Miner FAQ

**What is out-of-date?**
Unfortunately we don't allow distribution of binaries at the current moment. We will be working on ways to enable this in the future with reproducible builds or official tags.

**How should this page be updated?**
Remove link to gpu miner binary. Can leave the instructions on how to create a flight sheet, we just can't host the actual link.

**Comment by Juuddi** [comment]
As per a discussion we had with @mechanikalk and @alanorwick, the flight sheet inclusion in the FAQ has been green lit as it has the associated disclaimer. I have gone ahead and updated the `warning` to a `danger` to highlight the warning in this PR #73
