### ISSUE TITLE
Issue on docs - Typo in CUDA Keyring change section

### ISSUE THREAD

**Issue by NickTheGrizzly** [dominant-strategies/quai-docs#78]
Path: /guides/miner/ubuntu

In this section of the Quai Miner Setup Guide, it has a typo:
"This can be done by changing the /ubuntu2004/ to the version of Ubuntu you’re using in the keyring dowload link."

"dowload" should be "download"

Thanks for your hard work Quai team! :)

NickTheGrizzly

![Typo in CUDA version change section](https://github.com/user-attachments/assets/4c72aa48-0b5e-4f34-b99a-513cefaa676e)

**Comment by Juuddi** [comment]
Thanks for pointing this out, I'll get it fixed in the next PR. ❤️

**Comment by NickTheGrizzly** [comment]
Sure thing!

Keep up the great work! I have my Quai back up and running for the testnet
and can't wait for the future of Quai.
Hoping to get Quaioneer somehow as well! I have loved QUAI from the start
and will do all I can to help!

Cheers!
Nick Maurer (NickTheGrizzly)
