### ISSUE TITLE
🔗[https://qu.ai/docs/develop/tutorials/multi-chain.md/] In Smart Contracts/ Deploy Page

### ISSUE THREAD

**Issue by Khris5** [dominant-strategies/quai-docs#95]
**Where is the broken link?**
Page: (Smart Contracts/ Deploy)
Lines: (lines 38-39)

**What word(s) is/are incorrectly linked?**
Please paste the word or section of copy that is incorrectly linked.

**What is the CURRENT, broken link address you are directed to?**
https://qu.ai/docs/develop/tutorials/multi-chain.md/

**What is the CORRECT, updated link address you should have been directed to (If you don't know, put IDK)?**
IDK

**Is there any additional context that may be useful in resolving this issue?**
I think the link is correct but the page is broken

**Comment by maxbibeau** [comment]
Thank you for flagging this -- we will fix ASAP!
